#!/usr/bin/env sh

set -e
export PATH=node_modules/.bin:$PATH

if [ -z "${CI}" ]; then
    echo "Detected no CI-environment, will test with ts-node"
    
    env $(cat .env | grep -v "#" | xargs) PG_HOST=localhost TS_NODE_TRANSPILE_ONLY=true TS_NODE_FILES=true _mocha --exit --require ts-node/register 'src/**/*.spec.ts'
else
    echo "Detected CI-environment, will test directly"
    [ -f /wait ] && /wait
    TS_NODE_FILES=true MOCHA_FILE=coverage/tests/mocha/results.xml nyc _mocha --reporter mocha-junit-reporter 'dist/**/*.spec.js'
fi


