#!/usr/bin/env sh

set -e
export PATH=node_modules/.bin:$PATH

if [ -z "${CI}" ]; then
    echo "Detected no CI-environment, will test with ts-node"
    env-cmd mocha --exit --extension "ts" --node-option "loader=ts-node/esm" 'src/**/*.spec.ts'
else
    echo "Detected CI-environment, will test directly"
    env-cmd mocha --exit 'dist/**/*.spec.js'
fi


