#!/usr/bin/env sh

set -e
export PATH=node_modules/.bin:$PATH

if [ -z "${CI}" ]; then
    echo "Detected no CI-environment, will test with ts-node"
    
    env $(cat .env | grep -v "#" | xargs) NODE_OPTIONS="--loader ts-node/esm" PG_HOST=localhost mocha --exit 'src/**/*.spec.ts'
else
    echo "Detected CI-environment, will test directly"
    [ -f /wait ] && /wait
    env $(cat .env.test | grep -v "#" | xargs) MOCHA_FILE=coverage/tests/mocha/results.xml mocha --exit 'dist/**/*.spec.js'
fi


